### ISSUE TITLE
Got an error while setting up the GraphQL sandbox locally

### ISSUE THREAD

**Issue by mquandalle** [kadirahq/graphql-blog-schema#1]
Hi @arunoda,

I’ve also been very interested in GraphQL (and Meteor as you know :-)) and I’m amazed that you have created such a great resource to learn it and play with it. You are seriously amazing :-)

Anyway, here is my bug report. I’m encountering the following error after `npm start`ing the GraphQL sandbox of “Lesson 7” and opening htpp://localhost:3000 in the browser:

``` sh
➜  graphql-blog-schema git:(build-schema) npm start      

> react-hot-boilerplate@1.0.0 start /tmp/graphql-blog-schema
> node server.js

Listening at localhost:3000
Hash: c72938325318ca88342b
Version: webpack 1.12.2
Time: 2552ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.69 MB       0  [emitted]  main
chunk    {0} bundle.js (main) 1.53 MB [rendered]
    [0] multi main 52 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://localhost:3000 2.14 kB {0} [built]
    [2] ./~/url/url.js 22.3 kB {0} [built]
    [3] ./~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] ./~/querystring/index.js 127 bytes {0} [built]
    [6] ./~/querystring/decode.js 2.4 kB {0} [built]
    [7] ./~/querystring/encode.js 2.09 kB {0} [built]
    [8] ./~/socket.io-client/index.js 37 bytes {0} [built]
    [9] ./~/socket.io-client/lib/index.js 1.5 kB {0} [built]
   [10] ./~/socket.io-client/lib/url.js 1.53 kB {0} [built]
   [11] ./~/parseuri/index.js 690 bytes {0} [built]
   [12] ./~/socket.io-client/~/debug/debug.js 2.46 kB {0} [built]
   [13] ./~/socket.io-parser/index.js 7.63 kB {0} [built]
   [14] ./~/socket.io-parser/~/debug/debug.js 2.46 kB {0} [built]
   [15] ./~/json3/lib/json3.js 40.1 kB {0} [built]
   [16] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [17] ./~/isarray/index.js 120 bytes {0} [built]
   [18] ./~/component-emitter/index.js 3 kB {0} [built]
   [19] ./~/socket.io-parser/binary.js 3.84 kB {0} [built]
   [20] ./~/socket.io-parser/is-buffer.js 252 bytes {0} [built]
   [21] ./~/socket.io-client/lib/manager.js 11 kB {0} [built]
   [22] ./~/engine.io-client/index.js 38 bytes {0} [built]
   [23] ./~/engine.io-client/lib/index.js 140 bytes {0} [built]
   [24] ./~/engine.io-client/lib/socket.js 16.9 kB {0} [built]
   [25] ./~/engine.io-client/lib/transports/index.js 1.08 kB {0} [built]
   [26] ./~/engine.io-client/lib/xmlhttprequest.js 1.16 kB {0} [built]
   [27] ./~/has-cors/index.js 458 bytes {0} [built]
   [28] ./~/global/index.js 257 bytes {0} [built]
   [29] ./~/engine.io-client/lib/transports/polling-xhr.js 7.92 kB {0} [built]
   [30] ./~/engine.io-client/lib/transports/polling.js 4.85 kB {0} [built]
   [31] ./~/engine.io-client/lib/transport.js 2.74 kB {0} [built]
   [32] ./~/engine.io-parser/lib/browser.js 14.4 kB {0} [built]
   [33] ./~/engine.io-parser/lib/keys.js 297 bytes {0} [built]
   [34] ./~/has-binary/index.js 1.08 kB {0} [built]
   [35] ./~/arraybuffer.slice/index.js 725 bytes {0} [built]
   [36] ./~/base64-arraybuffer/lib/base64-arraybuffer.js 1.7 kB {0} [built]
   [37] ./~/after/index.js 685 bytes {0} [built]
   [38] ./~/utf8/utf8.js 6.38 kB {0} [built]
   [39] ./~/blob/index.js 2.2 kB {0} [built]
   [40] ./~/parseqs/index.js 708 bytes {0} [built]
   [41] ./~/component-inherit/index.js 146 bytes {0} [built]
   [42] ./~/engine.io-client/~/debug/browser.js 3.28 kB {0} [built]
   [43] ./~/engine.io-client/~/debug/debug.js 4.1 kB {0} [built]
   [44] ./~/engine.io-client/~/ms/index.js 2.02 kB {0} [built]
   [45] ./~/engine.io-client/lib/transports/polling-jsonp.js 4.82 kB {0} [built]
   [46] ./~/engine.io-client/lib/transports/websocket.js 4.57 kB {0} [built]
   [47] ./~/ws/lib/browser.js 831 bytes {0} [built]
   [48] ./~/indexof/index.js 199 bytes {0} [built]
   [49] ./~/engine.io-client/~/parseuri/index.js 1.19 kB {0} [built]
   [50] ./~/parsejson/index.js 842 bytes {0} [built]
   [51] ./~/socket.io-client/lib/socket.js 6.99 kB {0} [built]
   [52] ./~/to-array/index.js 216 bytes {0} [built]
   [53] ./~/socket.io-client/lib/on.js 370 bytes {0} [built]
   [54] ./~/component-bind/index.js 474 bytes {0} [built]
   [55] ./~/object-component/index.js 1.18 kB {0} [built]
   [56] ./~/backo2/index.js 1.4 kB {0} [built]
   [57] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [58] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [59] (webpack)/hot/only-dev-server.js 2.25 kB {0} [built]
   [60] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]
   [61] ./src/index.js 1.65 kB {0} [built]
   [62] ./~/react-hot-api/modules/index.js 57 bytes {0} [built]
   [63] ./~/react-hot-api/modules/makeMakeHot.js 1.07 kB {0} [built]
   [64] ./~/react-hot-api/modules/makePatchReactClass.js 1.3 kB {0} [built]
   [65] ./~/react-hot-api/modules/makeAssimilatePrototype.js 1.85 kB {0} [built]
   [66] ./~/react-hot-api/modules/requestForceUpdateAll.js 888 bytes {0} [built]
   [67] ./~/react-hot-api/modules/deepForceUpdate.js 1.23 kB {0} [built]
   [68] ./~/react-hot-api/modules/bindAutoBindMethods.js 2.21 kB {0} [built]
   [69] ./~/react-hot-api/modules/traverseRenderedChildren.js 536 bytes {0} [built]
   [70] ./~/react-hot-loader/RootInstanceProvider.js 1.18 kB {0} [built]
   [71] ./~/react-hot-loader/getRootInstancesFromReactMount.js 209 bytes {0} [built]
   [72] ./~/react/lib/ReactMount.js 31.2 kB {0} [built]
   [73] ./~/process/browser.js 2.06 kB {0} [built]
   [74] ./~/react/lib/DOMProperty.js 10.2 kB {0} [built]
   [75] ./~/react/lib/invariant.js 1.54 kB {0} [built]
   [76] ./~/react/lib/ReactBrowserEventEmitter.js 12.3 kB {0} [built]
   [77] ./~/react/lib/EventConstants.js 1.56 kB {0} [built]
   [78] ./~/react/lib/keyMirror.js 1.3 kB {0} [built]
   [79] ./~/react/lib/EventPluginHub.js 8.23 kB {0} [built]
   [80] ./~/react/lib/EventPluginRegistry.js 8.92 kB {0} [built]
   [81] ./~/react/lib/EventPluginUtils.js 6.75 kB {0} [built]
   [82] ./~/react/lib/accumulateInto.js 1.74 kB {0} [built]
   [83] ./~/react/lib/forEachAccumulated.js 889 bytes {0} [built]
   [84] ./~/react/lib/ReactEventEmitterMixin.js 1.32 kB {0} [built]
   [85] ./~/react/lib/ViewportMetrics.js 638 bytes {0} [built]
   [86] ./~/react/lib/Object.assign.js 1.26 kB {0} [built]
   [87] ./~/react/lib/isEventSupported.js 1.98 kB {0} [built]
   [88] ./~/react/lib/ExecutionEnvironment.js 1.13 kB {0} [built]
   [89] ./~/react/lib/ReactCurrentOwner.js 738 bytes {0} [built]
   [90] ./~/react/lib/ReactElement.js 8.27 kB {0} [built]
   [91] ./~/react/lib/ReactContext.js 1.97 kB {0} [built]
   [92] ./~/react/lib/emptyObject.js 483 bytes {0} [built]
   [93] ./~/react/lib/warning.js 1.9 kB {0} [built]
   [94] ./~/react/lib/emptyFunction.js 1.06 kB {0} [built]
   [95] ./~/react/lib/ReactElementValidator.js 14.2 kB {0} [built]
   [96] ./~/react/lib/ReactFragment.js 5.74 kB {0} [built]
   [97] ./~/react/lib/ReactPropTypeLocations.js 543 bytes {0} [built]
   [98] ./~/react/lib/ReactPropTypeLocationNames.js 612 bytes {0} [built]
   [99] ./~/react/lib/ReactNativeComponent.js 3.22 kB {0} [built]
  [100] ./~/react/lib/getIteratorFn.js 1.18 kB {0} [built]
  [101] ./~/react/lib/ReactEmptyComponent.js 2.83 kB {0} [built]
  [102] ./~/react/lib/ReactInstanceMap.js 1.25 kB {0} [built]
  [103] ./~/react/lib/ReactInstanceHandles.js 10.6 kB {0} [built]
  [104] ./~/react/lib/ReactRootIndex.js 723 bytes {0} [built]
  [105] ./~/react/lib/ReactMarkupChecksum.js 1.32 kB {0} [built]
  [106] ./~/react/lib/adler32.js 885 bytes {0} [built]
  [107] ./~/react/lib/ReactPerf.js 2.55 kB {0} [built]
  [108] ./~/react/lib/ReactReconciler.js 3.6 kB {0} [built]
  [109] ./~/react/lib/ReactRef.js 2 kB {0} [built]
  [110] ./~/react/lib/ReactOwner.js 3.69 kB {0} [built]
  [111] ./~/react/lib/ReactUpdateQueue.js 9.95 kB {0} [built]
  [112] ./~/react/lib/ReactLifeCycle.js 1.25 kB {0} [built]
  [113] ./~/react/lib/ReactUpdates.js 9.26 kB {0} [built]
  [114] ./~/react/lib/CallbackQueue.js 2.47 kB {0} [built]
  [115] ./~/react/lib/PooledClass.js 3.27 kB {0} [built]
  [116] ./~/react/lib/Transaction.js 9.36 kB {0} [built]
  [117] ./~/react/lib/containsNode.js 1.23 kB {0} [built]
  [118] ./~/react/lib/isTextNode.js 614 bytes {0} [built]
  [119] ./~/react/lib/isNode.js 718 bytes {0} [built]
  [120] ./~/react/lib/getReactRootElementInContainer.js 888 bytes {0} [built]
  [121] ./~/react/lib/instantiateReactComponent.js 4.59 kB {0} [built]
  [122] ./~/react/lib/ReactCompositeComponent.js 29.4 kB {0} [built]
  [123] ./~/react/lib/ReactComponentEnvironment.js 1.7 kB {0} [built]
  [124] ./~/react/lib/shouldUpdateReactComponent.js 4.09 kB {0} [built]
  [125] ./~/react/lib/setInnerHTML.js 3.03 kB {0} [built]
  [126] ./~/react/react.js 41 bytes {0} [built]
  [127] ./~/react/lib/React.js 4.79 kB {0} [built]
  [128] ./~/react/lib/ReactChildren.js 4.74 kB {0} [built]
  [129] ./~/react/lib/traverseAllChildren.js 7.54 kB {0} [built]
  [130] ./~/react/lib/ReactComponent.js 5.04 kB {0} [built]
  [131] ./~/react/lib/ReactClass.js 30 kB {0} [built]
  [132] ./~/react/lib/ReactErrorUtils.js 843 bytes {0} [built]
  [133] ./~/react/lib/keyOf.js 1.1 kB {0} [built]
  [134] ./~/react/lib/ReactDOM.js 3.29 kB {0} [built]
  [135] ./~/react/lib/mapObject.js 1.47 kB {0} [built]
  [136] ./~/react/lib/ReactDOMTextComponent.js 3.59 kB {0} [built]
  [137] ./~/react/lib/DOMPropertyOperations.js 6.03 kB {0} [built]
  [138] ./~/react/lib/quoteAttributeValueForBrowser.js 747 bytes {0} [built]
  [139] ./~/react/lib/escapeTextContentForBrowser.js 850 bytes {0} [built]
  [140] ./~/react/lib/ReactComponentBrowserEnvironment.js 1.29 kB {0} [built]
  [141] ./~/react/lib/ReactDOMIDOperations.js 5.49 kB {0} [built]
  [142] ./~/react/lib/CSSPropertyOperations.js 5.31 kB {0} [built]
  [143] ./~/react/lib/CSSProperty.js 3.14 kB {0} [built]
  [144] ./~/react/lib/camelizeStyleName.js 1.03 kB {0} [built]
  [145] ./~/react/lib/camelize.js 714 bytes {0} [built]
  [146] ./~/react/lib/dangerousStyleValue.js 1.93 kB {0} [built]
  [147] ./~/react/lib/hyphenateStyleName.js 1.01 kB {0} [built]
  [148] ./~/react/lib/hyphenate.js 808 bytes {0} [built]
  [149] ./~/react/lib/memoizeStringOnly.js 778 bytes {0} [built]
  [150] ./~/react/lib/DOMChildrenOperations.js 4.51 kB {0} [built]
  [151] ./~/react/lib/Danger.js 7.19 kB {0} [built]
  [152] ./~/react/lib/createNodesFromMarkup.js 2.69 kB {0} [built]
  [153] ./~/react/lib/createArrayFromMixed.js 2.37 kB {0} [built]
  [154] ./~/react/lib/toArray.js 2.08 kB {0} [built]
  [155] ./~/react/lib/getMarkupWrap.js 3.16 kB {0} [built]
  [156] ./~/react/lib/ReactMultiChildUpdateTypes.js 835 bytes {0} [built]
  [157] ./~/react/lib/setTextContent.js 1.19 kB {0} [built]
  [158] ./~/react/lib/ReactDOMComponent.js 17 kB {0} [built]
  [159] ./~/react/lib/ReactMultiChild.js 12 kB {0} [built]
  [160] ./~/react/lib/ReactChildReconciler.js 4.17 kB {0} [built]
  [161] ./~/react/lib/flattenChildren.js 1.68 kB {0} [built]
  [162] ./~/react/lib/ReactDefaultInjection.js 5.44 kB {0} [built]
  [163] ./~/react/lib/BeforeInputEventPlugin.js 15.1 kB {0} [built]
  [164] ./~/react/lib/EventPropagators.js 4.65 kB {0} [built]
  [165] ./~/react/lib/FallbackCompositionState.js 2.38 kB {0} [built]
  [166] ./~/react/lib/getTextContentAccessor.js 1 kB {0} [built]
  [167] ./~/react/lib/SyntheticCompositionEvent.js 1.14 kB {0} [built]
  [168] ./~/react/lib/SyntheticEvent.js 4.85 kB {0} [built]
  [169] ./~/react/lib/getEventTarget.js 931 bytes {0} [built]
  [170] ./~/react/lib/SyntheticInputEvent.js 1.12 kB {0} [built]
  [171] ./~/react/lib/ChangeEventPlugin.js 11.5 kB {0} [built]
  [172] ./~/react/lib/isTextInputElement.js 975 bytes {0} [built]
  [173] ./~/react/lib/ClientReactRootIndex.js 551 bytes {0} [built]
  [174] ./~/react/lib/DefaultEventPluginOrder.js 1.34 kB {0} [built]
  [175] ./~/react/lib/EnterLeaveEventPlugin.js 3.86 kB {0} [built]
  [176] ./~/react/lib/SyntheticMouseEvent.js 2.2 kB {0} [built]
  [177] ./~/react/lib/SyntheticUIEvent.js 1.6 kB {0} [built]
  [178] ./~/react/lib/getEventModifierState.js 1.33 kB {0} [built]
  [179] ./~/react/lib/HTMLDOMPropertyConfig.js 6.53 kB {0} [built]
  [180] ./~/react/lib/MobileSafariClickEventPlugin.js 1.72 kB {0} [built]
  [181] ./~/react/lib/ReactBrowserComponentMixin.js 715 bytes {0} [built]
  [182] ./~/react/lib/findDOMNode.js 2.4 kB {0} [built]
  [183] ./~/react/lib/ReactDefaultBatchingStrategy.js 1.91 kB {0} [built]
  [184] ./~/react/lib/ReactDOMButton.js 1.61 kB {0} [built]
  [185] ./~/react/lib/AutoFocusMixin.js 595 bytes {0} [built]
  [186] ./~/react/lib/focusNode.js 728 bytes {0} [built]
  [187] ./~/react/lib/ReactDOMForm.js 1.64 kB {0} [built]
  [188] ./~/react/lib/LocalEventTrapMixin.js 1.74 kB {0} [built]
  [189] ./~/react/lib/ReactDOMImg.js 1.41 kB {0} [built]
  [190] ./~/react/lib/ReactDOMIframe.js 1.37 kB {0} [built]
  [191] ./~/react/lib/ReactDOMInput.js 5.91 kB {0} [built]
  [192] ./~/react/lib/LinkedValueUtils.js 4.75 kB {0} [built]
  [193] ./~/react/lib/ReactPropTypes.js 11.1 kB {0} [built]
  [194] ./~/react/lib/ReactDOMOption.js 1.34 kB {0} [built]
  [195] ./~/react/lib/ReactDOMSelect.js 5.21 kB {0} [built]
  [196] ./~/react/lib/ReactDOMTextarea.js 4.71 kB {0} [built]
  [197] ./~/react/lib/ReactEventListener.js 5.51 kB {0} [built]
  [198] ./~/react/lib/EventListener.js 2.67 kB {0} [built]
  [199] ./~/react/lib/getUnboundedScrollPosition.js 1.09 kB {0} [built]
  [200] ./~/react/lib/ReactInjection.js 1.47 kB {0} [built]
  [201] ./~/react/lib/ReactReconcileTransaction.js 4.92 kB {0} [built]
  [202] ./~/react/lib/ReactInputSelection.js 4.25 kB {0} [built]
  [203] ./~/react/lib/ReactDOMSelection.js 6.14 kB {0} [built]
  [204] ./~/react/lib/getNodeForCharacterOffset.js 1.66 kB {0} [built]
  [205] ./~/react/lib/getActiveElement.js 788 bytes {0} [built]
  [206] ./~/react/lib/ReactPutListenerQueue.js 1.33 kB {0} [built]
  [207] ./~/react/lib/SelectEventPlugin.js 5.84 kB {0} [built]
  [208] ./~/react/lib/shallowEqual.js 1.1 kB {0} [built]
  [209] ./~/react/lib/ServerReactRootIndex.js 868 bytes {0} [built]
  [210] ./~/react/lib/SimpleEventPlugin.js 12.5 kB {0} [built]
  [211] ./~/react/lib/SyntheticClipboardEvent.js 1.22 kB {0} [built]
  [212] ./~/react/lib/SyntheticFocusEvent.js 1.08 kB {0} [built]
  [213] ./~/react/lib/SyntheticKeyboardEvent.js 2.72 kB {0} [built]
  [214] ./~/react/lib/getEventCharCode.js 1.56 kB {0} [built]
  [215] ./~/react/lib/getEventKey.js 2.93 kB {0} [built]
  [216] ./~/react/lib/SyntheticDragEvent.js 1.09 kB {0} [built]
  [217] ./~/react/lib/SyntheticTouchEvent.js 1.3 kB {0} [built]
  [218] ./~/react/lib/SyntheticWheelEvent.js 1.99 kB {0} [built]
  [219] ./~/react/lib/SVGDOMPropertyConfig.js 2.8 kB {0} [built]
  [220] ./~/react/lib/createFullPageComponent.js 1.9 kB {0} [built]
  [221] ./~/react/lib/ReactDefaultPerf.js 8.55 kB {0} [built]
  [222] ./~/react/lib/ReactDefaultPerfAnalysis.js 5.67 kB {0} [built]
  [223] ./~/react/lib/performanceNow.js 767 bytes {0} [built]
  [224] ./~/react/lib/performance.js 625 bytes {0} [built]
  [225] ./~/react/lib/ReactServerRendering.js 2.58 kB {0} [built]
  [226] ./~/react/lib/ReactServerRenderingTransaction.js 2.72 kB {0} [built]
  [227] ./~/react/lib/onlyChild.js 1.23 kB {0} [built]
  [228] ./src/App.js 4.48 kB {0} [built] [1 error]
  [229] ./~/graphiql/dist/index.js 322 bytes {0} [built]
  [230] ./~/graphiql/dist/components/GraphiQL.js 23.7 kB {0} [built] [3 errors]
  [231] ./~/graphiql/dist/components/ExecuteButton.js 3.22 kB {0} [built]
  [232] ./~/graphiql/dist/components/QueryEditor.js 10.7 kB {0} [built] [1 error]
  [233] ./~/marked/lib/marked.js 28.6 kB {0} [built]
  [234] ./~/codemirror/lib/codemirror.js 350 kB {0} [built]
  [235] ./~/codemirror/addon/hint/show-hint.js 14.4 kB {0} [built]
  [236] ./~/codemirror/addon/comment/comment.js 8.01 kB {0} [built]
  [237] ./~/codemirror/addon/edit/matchbrackets.js 5.25 kB {0} [built]
  [238] ./~/codemirror/addon/edit/closebrackets.js 6.93 kB {0} [built]
  [239] ./~/codemirror/addon/fold/foldgutter.js 4.63 kB {0} [built]
  [240] ./~/codemirror/addon/fold/foldcode.js 4.69 kB {0} [built]
  [241] ./~/codemirror/addon/fold/brace-fold.js 3.9 kB {0} [built]
  [242] ./~/codemirror/addon/lint/lint.js 7.8 kB {0} [built]
  [243] ./~/codemirror/keymap/sublime.js 21.3 kB {0} [built]
  [244] ./~/codemirror/addon/search/searchcursor.js 7.72 kB {0} [built]
  [245] ./~/codemirror-graphql/hint.js 12.9 kB {0} [built] [2 errors]
  [246] ./~/codemirror-graphql/lint.js 2.36 kB {0} [built] [2 errors]
  [247] ./~/codemirror-graphql/mode.js 12.4 kB {0} [built]
  [248] ./~/graphiql/dist/components/VariableEditor.js 4.95 kB {0} [built]
  [249] ./~/codemirror/mode/javascript/javascript.js 26.8 kB {0} [built]
  [250] ./~/graphiql/dist/codemirror/lint/json-lint.js 1.09 kB {0} [built]
  [251] ./~/graphiql/dist/codemirror/lint/jsonLint.js 4.39 kB {0} [built]
  [252] ./~/graphiql/dist/components/ResultViewer.js 3.73 kB {0} [built]
  [253] ./~/graphiql/dist/components/DocExplorer.js 16.4 kB {0} [built] [1 error]
  [254] ./~/graphiql/dist/utility/fillLeafs.js 5.08 kB {0} [built] [3 errors]
  [255] ./~/graphiql/dist/utility/elementPosition.js 741 bytes {0} [built]
  [256] ./~/isomorphic-fetch/fetch-npm-browserify.js 233 bytes {0} [built]
  [257] ./~/whatwg-fetch/fetch.js 8.54 kB {0} [built]
  [258] ./src/schema.js 2.98 kB {0} [built] [1 error]
  [259] ./~/underscore/underscore.js 52.9 kB {0} [built]
  [260] ./src/data/posts.js 28.7 kB {0} [built]
  [261] ./~/react-hot-loader/makeExportsHot.js 1.69 kB {0} [built]
  [262] ./~/react-hot-loader/isReactClassish.js 801 bytes {0} [built]
  [263] ./~/react-hot-loader/isReactElementish.js 288 bytes {0} [built]
  [264] ./src/data/authors.js 1.73 kB {0} [built]
  [265] ./src/data/comments.js 1.97 kB {0} [built]

ERROR in ./src/App.js
Module not found: Error: Cannot resolve module 'graphql' in /tmp/graphql-blog-schema/src
 @ ./src/App.js 35:11-29

ERROR in ./src/schema.js
Module not found: Error: Cannot resolve module 'graphql' in /tmp/graphql-blog-schema/src
 @ ./src/schema.js 29:15-33

ERROR in ./~/graphiql/dist/components/GraphiQL.js
Module not found: Error: Cannot resolve module 'graphql/type' in /tmp/graphql-blog-schema/node_modules/graphiql/dist/components
 @ ./~/graphiql/dist/components/GraphiQL.js 35:19-42

ERROR in ./~/graphiql/dist/components/GraphiQL.js
Module not found: Error: Cannot resolve module 'graphql/utilities' in /tmp/graphql-blog-schema/node_modules/graphiql/dist/components
 @ ./~/graphiql/dist/components/GraphiQL.js 37:24-52

ERROR in ./~/graphiql/dist/components/GraphiQL.js
Module not found: Error: Cannot resolve module 'graphql/jsutils/find' in /tmp/graphql-blog-schema/node_modules/graphiql/dist/components
 @ ./~/graphiql/dist/components/GraphiQL.js 39:26-57

ERROR in ./~/graphiql/dist/components/QueryEditor.js
Module not found: Error: Cannot resolve module 'graphql/type' in /tmp/graphql-blog-schema/node_modules/graphiql/dist/components
 @ ./~/graphiql/dist/components/QueryEditor.js 33:19-42

ERROR in ./~/graphiql/dist/components/DocExplorer.js
Module not found: Error: Cannot resolve module 'graphql/type' in /tmp/graphql-blog-schema/node_modules/graphiql/dist/components
 @ ./~/graphiql/dist/components/DocExplorer.js 29:19-42

ERROR in ./~/graphiql/dist/utility/fillLeafs.js
Module not found: Error: Cannot resolve module 'graphql/utilities' in /tmp/graphql-blog-schema/node_modules/graphiql/dist/utility
 @ ./~/graphiql/dist/utility/fillLeafs.js 14:24-52

ERROR in ./~/graphiql/dist/utility/fillLeafs.js
Module not found: Error: Cannot resolve module 'graphql/language' in /tmp/graphql-blog-schema/node_modules/graphiql/dist/utility
 @ ./~/graphiql/dist/utility/fillLeafs.js 16:23-50

ERROR in ./~/graphiql/dist/utility/fillLeafs.js
Module not found: Error: Cannot resolve module 'graphql/type' in /tmp/graphql-blog-schema/node_modules/graphiql/dist/utility
 @ ./~/graphiql/dist/utility/fillLeafs.js 18:19-42

ERROR in ./~/codemirror-graphql/hint.js
Module not found: Error: Cannot resolve module 'graphql/type' in /tmp/graphql-blog-schema/node_modules/codemirror-graphql
 @ ./~/codemirror-graphql/hint.js 18:19-42

ERROR in ./~/codemirror-graphql/hint.js
Module not found: Error: Cannot resolve module 'graphql/type/introspection' in /tmp/graphql-blog-schema/node_modules/codemirror-graphql
 @ ./~/codemirror-graphql/hint.js 20:32-69

ERROR in ./~/codemirror-graphql/lint.js
Module not found: Error: Cannot resolve module 'graphql/language' in /tmp/graphql-blog-schema/node_modules/codemirror-graphql
 @ ./~/codemirror-graphql/lint.js 18:23-50

ERROR in ./~/codemirror-graphql/lint.js
Module not found: Error: Cannot resolve module 'graphql/validation' in /tmp/graphql-blog-schema/node_modules/codemirror-graphql
 @ ./~/codemirror-graphql/lint.js 20:25-54
webpack: bundle is now VALID.
```

Maybe this is due to my node or npm versions?

```
➜ node --version
v0.12.7
➜ npm --version
3.3.5
```

**Comment by arunoda** [comment]
Okay. That's because of npm 3. We need to define peerDependencies. Let me fix it.

**Comment by arunoda** [comment]
Check now. 
Thanks for the props :)

**Comment by arunoda** [comment]
BTW: Give us a little review: https://learngraphql.com/reviews :)

**Comment by mquandalle** [comment]
3cf03408edbaaeb1d0a681dbbfea8705ed926faa fixed it, thanks :-)

**Comment by mquandalle** [comment]
Here is another one on the `server-side-schema` branch:

```
➜  graphql-blog-schema git:(server-side-schema) ✗ npm install
npm WARN install Couldn't install optional dependency: Unsupported

> bufferutil@1.2.1 install /tmp/graphql-blog-schema/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/tmp/graphql-blog-schema/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/tmp/graphql-blog-schema/node_modules/bufferutil/build'

> kerberos@0.0.15 install /tmp/graphql-blog-schema/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/tmp/graphql-blog-schema/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: Aucun fichier ou dossier de ce type
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:93: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/tmp/graphql-blog-schema/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.2-040102-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/graphql-blog-schema/node_modules/kerberos
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN prefer global marked@0.3.5 should be installed with -g

> utf-8-validate@1.2.1 install /tmp/graphql-blog-schema/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/tmp/graphql-blog-schema/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/tmp/graphql-blog-schema/node_modules/utf-8-validate/build'
npm WARN EPEERINVALID eslint-plugin-react@2.7.1 requires a peer of eslint@>=0.8.0 || ~1.0.0-rc-0 but none was installed.
```

**Comment by arunoda** [comment]
Hey, are you sure we are on the correct branch. This version does not have eslint related plugins anyway. Could you remove `node_modules` directory and try out again.

**Comment by arunoda** [comment]
May be try using Node 4.2.0

**Comment by mquandalle** [comment]
I still get an error on Node 4 (after removing `nodes_modules`):

```
➜  graphql-blog-schema git:(server-side-schema) ✗ npm install        

> kerberos@0.0.15 install /tmp/graphql-blog-schema/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/tmp/graphql-blog-schema/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: Aucun fichier ou dossier de ce type
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/tmp/graphql-blog-schema/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/maxime/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.2-040102-generic
gyp ERR! command "/home/maxime/.nvm/versions/node/v4.0.0/bin/node" "/home/maxime/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/graphql-blog-schema/node_modules/kerberos
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
```

**Comment by arunoda** [comment]
Hmm. That's the node issue failing here. Let me google it.

**Comment by mquandalle** [comment]
Yep `apt-get install libkrb5-dev` fixed it, but it’s a bit confusing.

**Comment by arunoda** [comment]
Yeah! I saw that. So weird. I didn't get this on mac. 
I think this is something mongo uses.

**Comment by mquandalle** [comment]
I’m on Ubuntu

**Comment by arunoda** [comment]
Yeah! Got it.

**Comment by arunoda** [comment]
See more on this: https://github.com/christkv/kerberos/issues/21
(BTW: See that's why Meteor packaging is great)

**Comment by mquandalle** [comment]
(Yep, I was about to say the same thing about Meteor packaging. I had so many non deterministic bugs with NPM...)

**Comment by arunoda** [comment]
Shall we close this issue?

**Comment by mquandalle** [comment]
It’s still an issue but I guess you can’t do much about it. (Also the Graph_i_QL client still can’t connect to the server on my side in this `server-side-schema` apparently)

**Comment by arunoda** [comment]
Hmmm
