### ISSUE TITLE
Babel Error after switching to 'defining-mutations'

### ISSUE THREAD

**Issue by idkjs** [kadirahq/graphql-blog-schema#14]
This is the error(second snippet) i get after following these steps.https://learngraphql.com/basics/defining-mutations/1

I tried installing https://babeljs.io/docs/plugins/preset-stage-0/ and editing the babelrc file to look like

```
{
  "presets": ["stage-0"]
}


ERROR in ./src/index.js
Module build failed: ReferenceError: [BABEL] /Users/klik/projects/graphql-blog-schema/src/index.js: Unknown option: /Users/klik/projects/.babelrc.presets
    at Logger.error (/Users/klik/projects/graphql-blog-schema/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/klik/projects/graphql-blog-schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/klik/projects/graphql-blog-schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/klik/projects/graphql-blog-schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/klik/projects/graphql-blog-schema/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/klik/projects/graphql-blog-schema/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/klik/projects/graphql-blog-schema/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/klik/projects/graphql-blog-schema/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/klik/projects/graphql-blog-schema/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/klik/projects/graphql-blog-schema/node_modules/babel-loader/index.js:71:12)
 @ multi main
webpack: bundle is now VALID.


```

**Comment by idkjs** [comment]
Still same issue.

**Comment by peterpeerdeman** [comment]
+1

edit: I did a `git reset --hard` on the `build-schema` branch, ran a new `npm install` and then ran `npm run` afterwards, which then worked for me
