### ISSUE TITLE
Cant't start the application

### ISSUE THREAD

**Issue by nysthee** [kadirahq/graphql-blog-schema#15]
When running `npm start` after `npm install` I get given error:

``` bash
> react-hot-boilerplate@1.0.0 start /Users/thomas/Dropbox/code/graphql/graphql-blog-schema
> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:84:10)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/thomas/.nvm/versions/node/v6.2.2/bin/node" "/Users/thomas/.nvm/versions/node/v6.2.2/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-hot-boilerplate@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-hot-boilerplate@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-hot-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-hot-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-hot-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thomas/Dropbox/code/graphql/graphql-blog-schema/npm-debug.log
``

Am I doing something wrong?
```

**Comment by idkjs** [comment]
You probably have a server already running on that port.
